In [5]:
import numpy as np

In [6]:

#1. Create an array from a Python list(1D)

array1=np.array([2,4,5,6,7,2])
array1

array([2, 4, 5, 6, 7, 2])

In [7]:
#2. Create a 2D array (matrix) array
array2=np.array([[1,2,3],[7,8,9],[5,6,4]])
array2

array([[1, 2, 3],
       [7, 8, 9],
       [5, 6, 4]])

In [8]:
#3.Check the shape of the array.

print(array2.shape)

(3, 3)


In [9]:
#4.Check the data type of array elements.
print(array2.dtype)

int64


In [10]:
#5.Reshape a 1D array of size 9 into a 3x3 matrix.
array1.reshape(3,2)

array([[2, 4],
       [5, 6],
       [7, 2]])

In [11]:
#6.Access the element at row 2, column 3 in a 2D array.
# for i in array2:
#     print(i)
array2[1][2]

np.int64(9)

In [12]:
#7.Replace a specific element in a 2D array.
array2[2][2]=56
print(array2)

[[ 1  2  3]
 [ 7  8  9]
 [ 5  6 56]]


In [13]:
#8.Slice the first two rows and columns of a 3x3 matrix.
result = array2[0:2,0:2]
result

array([[1, 2],
       [7, 8]])

In [14]:
#9.Add two arrays element-wise.
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([2,3,5,4,8,6])



In [15]:
#10.Multiply two arrays element-wise.
result=(arr1 * arr2)
result

array([ 2,  6, 15, 16, 40, 36])

In [16]:
#11.Square every element in an array.
print(array1)
res=array1**2
res

[2 4 5 6 7 2]


array([ 4, 16, 25, 36, 49,  4])

In [17]:
#12.Find the sum of all elements in an array.
result=np.sum(array1)
result


np.int64(26)

In [18]:
#13.Create an array of 5 random integers between 1 and 10.
rnum=np.random.randint(1,10)
rnum

2

In [19]:
#14.Shuffle a NumPy array.
np.random.shuffle(arr1) 
arr1

array([2, 6, 5, 1, 4, 3])

In [20]:
#15.Generate 1000 random numbers and find the mean

mean_value = np.random.randn(1000).mean()
mean_value


np.float64(0.009238466480358939)

In [21]:
#16.Sort array in ascending orde

np.sort(array1)

array([2, 2, 4, 5, 6, 7])

In [22]:
#17.Search specific element in an array
np.where(arr1==3)


(array([5]),)

In [23]:
#18. Filter an array by even numbers

evennum=array1[array1 % 2 ==0]
evennum

array([2, 4, 6, 2])

In [24]:
#19. Create 3x3 matrix and iterate matrix thro. for loop

arr=np.array([[[2,3,4],[5,8,7],[3,4,6]],[[8,5,2,],[7,4,1],[3,2,1]],[[3,6,5],[8,7,4],[1,5,9]]])
for i in arr:
    for j in i:
        for k in j:
            print(k,end=" ")
        print()
    print()

2 3 4 
5 8 7 
3 4 6 

8 5 2 
7 4 1 
3 2 1 

3 6 5 
8 7 4 
1 5 9 



In [25]:
#20. print row wise addition of 2D matrix
for i in arr:
    for j in i:
        sum=0
        for k in j:
            sum+=k
            print(k,end=" ")
        print('=',sum)
    print()

2 3 4 = 9
5 8 7 = 20
3 4 6 = 13

8 5 2 = 15
7 4 1 = 12
3 2 1 = 6

3 6 5 = 14
8 7 4 = 19
1 5 9 = 15

