In [2]:
import numpy  as np 
arr1=np.array(5)
arr1 
print(arr1.ndim)

0


In [3]:
arr2=np.array([20,30,40,50,60,70])
print(arr2)
print(arr2.ndim)
print(arr2[2] + arr2[3])
for i in arr2:
    print(i)

[20 30 40 50 60 70]
1
90
20
30
40
50
60
70


In [6]:
sum=0
sum1=0
for i in arr2:
    sum+=i
    if i%3==0 and i%5==0:
        sum1=sum1+i
print('sum of array=',sum)
print('divisible by 3 and 5 number addtion=',sum1)


sum of array= 270
divisible by 3 and 5 number addtion= 90


In [16]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in arr2:
    for j in i:
        print(j,end=" ")
    print()    

1 2 3 
4 5 6 
7 8 9 


In [18]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print('addition:',a+b)
print(a*b)
print(a**b)

addition: [5 7 9]
[ 4 10 18]
[  1  32 729]


In [27]:
a1=np.array([[1,2,3,4],[5,6,7,8]])
b2=np.array([[4,5,6,1],[2,3,7,8]])
print(a1.ndim)
print(np.sum(a1+b2,axis=0))
for i in a1:
    for j in i:
        print(j,end=" ")
    print()
print("*"*40)
for i in b2:
    for j in i:
        print(j,end=" ")
    print()
print("*"*40)
print(np.sum(a1+b2,axis=1))

2
[12 16 23 21]
1 2 3 4 
5 6 7 8 
****************************************
4 5 6 1 
2 3 7 8 
****************************************
[26 46]


In [ ]:
arr=np.array([[2,4,5],[2,3,7],[3,4,2],[5,7,3]])
print(np.sum(arr,axis=0))
print(np.sum,'sdss'(arr,axis=1))

[12 18 17]
[11 12  9 15]


In [35]:
print(np.min(arr))
print(np.max(arr))

2
7


In [ ]:
sum=0
D1=np.array([1,2,3,4,5,6,7,8])
for i in D1:
    sum+=i
print('sum of 1 d array:',sum)

sum of 1 d array 36


In [ ]:
sum=0
matrixs=np.array([1,2,3,4,5,6,7,8,9,10])
lenth=len(matrixs)
for i in range(0,lenth+1,3):
    sum+=i
print(sum)


30


In [ ]:
cource=np.array(["BCA","Btech","engineering"])
for i in cource:
    

3
3
3


In [51]:
print(np.average(matrixs))

5.5


In [52]:

cource=np.array(["BCA","Btech","engineering"])
for i in cource[: :-1]:
    print(i)


engineering
Btech
BCA


In [55]:
count=0
for i in cource:
    for j in i:
        count+=1
print(count)

19


In [56]:
arr=np.array([2,'vaibhav',4.5])
for i in arr:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [57]:
arr1=np.array([2,3,4,5])
arr2=np.array([4,5,6,7])
print(arr1+arr2)

[ 6  8 10 12]


In [58]:
print(arr1*2)

[ 4  6  8 10]
