In [2]:
import numpy as np
arr=np.arange(50,101)
arr1=np.arange(10,51,2)

arr1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [4]:
np.linspace(3,10,10)
np.random.rand(100)
np.random.randint(100,200,10)


array([120, 132, 104, 174, 128, 151, 110, 110, 195, 176], dtype=int32)

In [7]:
newArr=np.array([4,2,3,56,54,45,13,17])
a=np.where(newArr%2!=0)
a

(array([2, 5, 6, 7]),)

In [8]:
newArr=np.array([4,2,3,56,54,45,13,17])
a=np.where(newArr%2==0)
a

(array([0, 1, 3, 4]),)

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
np.full((4,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [17]:
arraynew=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[5,2,4],[3,8,7],[2,4,6]],[[8,7,9],[3,4,7],[6,4,9]]])
print(arraynew)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[5 2 4]
  [3 8 7]
  [2 4 6]]

 [[8 7 9]
  [3 4 7]
  [6 4 9]]]


In [19]:
print(arraynew[0,2,2])

9


In [20]:
print(arraynew[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print(arraynew[0,2])

[7 8 9]


In [22]:
print(arraynew[0,2,0])

7


In [24]:
array2=np.array([2,4,5,6,7,8,9,4,3,6])
array2.reshape(5,2)

array([[2, 4],
       [5, 6],
       [7, 8],
       [9, 4],
       [3, 6]])

In [25]:
array2.reshape(2,5)

array([[2, 4, 5, 6, 7],
       [8, 9, 4, 3, 6]])