In [3]:
import numpy as np 
arr=np.array([[[2,3,4],[5,8,7],[3,4,6]],[[8,5,2,],[7,4,1],[3,2,1]],[[3,6,5],[8,7,4],[1,5,9]]])

In [6]:
for i in arr:
    print(i)
    print('*'*50)

[[2 3 4]
 [5 8 7]
 [3 4 6]]
**************************************************
[[8 5 2]
 [7 4 1]
 [3 2 1]]
**************************************************
[[3 6 5]
 [8 7 4]
 [1 5 9]]
**************************************************


In [7]:
for i in arr:
    for j in i:
        print(j,end=" ")
    print()

[2 3 4] [5 8 7] [3 4 6] 
[8 5 2] [7 4 1] [3 2 1] 
[3 6 5] [8 7 4] [1 5 9] 


In [8]:
for i in arr:
    for j in i:
        for k in j:
            print(k,end=" ")
        print()
    print()

2 3 4 
5 8 7 
3 4 6 

8 5 2 
7 4 1 
3 2 1 

3 6 5 
8 7 4 
1 5 9 



In [12]:
for i in arr:
    for j in i:
        sum=0
        for k in j:
            sum+=k
            print(k,end=" ")
        print("=",sum)
    print()

2 3 4 = 9
5 8 7 = 20
3 4 6 = 13

8 5 2 = 15
7 4 1 = 12
3 2 1 = 6

3 6 5 = 14
8 7 4 = 19
1 5 9 = 15



In [14]:
for i in arr:
    for j in i:
        sum=0
        for k in j[ ::-1]:
            sum+=k
            print(k,end=" ")
        print("=",sum)
    print()

4 3 2 = 9
7 8 5 = 20
6 4 3 = 13

2 5 8 = 15
1 4 7 = 12
1 2 3 = 6

5 6 3 = 14
4 7 8 = 19
9 5 1 = 15



In [19]:
narr=np.array([34,12,55,68,9,17,10,100,60,27,95,88])
newarr=narr[narr>50]
print(newarr)

[ 55  68 100  60  95  88]
